---

mon_postgres_exporter: 0.17.1
patroni_ver: 3.3.4
ydiff_ver: 1.3


app_db: app
app_user: app
app_passwd: app

pgbouncer_ssl: 1
patroni_ssl: 1

sysctl:
  - { name: 'vm.swappiness', value: '0' }
  - { name: 'vm.file-max', value: '3048576' }
  - { name: 'vm.nr_open', value: '3048576' }
  - { name: 'vm.nr_hugepages', value: '95' }

patroni_scope: cluster
patroni_raft_cluster: "{{ groups['raft_cluster_01'] }}"
pg_cluster: "{{ groups['postgresql_cluster_01'] }}"
pg_config:
  - { name: max_connections, value: "{{ db_connections }}", for_patroni: 1 }
  - { name: log_directory, value: "'/var/log/postgresql'", for_patroni: 1 }
  - { name: log_file_mode, value: "'0644'", for_patroni: 1 }
  - { name: log_filename, value: "'postgresql-%a.log'", for_patroni: 1 }
  - { name: log_rotation_age, value: "1d", for_patroni: 1 }
  - { name: log_rotation_size, value: "0", for_patroni: 1 }
  - { name: log_truncate_on_rotation, value: "on", for_patroni: 1 }
  - { name: max_wal_size, value: "1GB", for_patroni: 1 }
  - { name: min_wal_size, value: "80MB", for_patroni: 1 }
  - { name: log_line_prefix, value: "'%m [%p] %q%u@%d '", for_patroni: 1 }
  - { name: log_duration, value: "'on'", for_patroni: 1 }
  - { name: log_statement, value: "'none'", for_patroni: 1 }
  - { name: log_min_duration_statement, value: "0", for_patroni: 1 }
  - { name: log_checkpoints, value: "'on'", for_patroni: 1 }
  - { name: log_connections, value: "'on'", for_patroni: 1 }
  - { name: log_disconnections, value: "'on'", for_patroni: 1 }
  - { name: log_lock_waits, value: "'on'", for_patroni: 1 }
  - { name: log_timezone, value: "'UTC+3'", for_patroni: 1 }
  - { name: timezone, value: "'UTC+3'", for_patroni: 1 }
  - { name: datestyle, value: "'iso, mdy'", for_patroni: 1 }
  - { name: lc_messages, value: "'en_US.UTF-8'", for_patroni: 1 }
  - { name: lc_monetary, value: "'en_US.UTF-8'", for_patroni: 1 }
  - { name: lc_numeric, value: "'en_US.UTF-8'", for_patroni: 1 }
  - { name: lc_time, value: "'en_US.UTF-8'", for_patroni: 1 }
  - { name: default_text_search_config, value: "'pg_catalog.english'", for_patroni: 1 }
  - { name: hot_standby, value: "on", for_patroni: 1 }
  - { name: wal_level, value: "replica", for_patroni: 1 }
  - { name: max_wal_senders, value: "10", for_patroni: 1 }
  - { name: hot_standby_feedback, value: "on", for_patroni: 1 }
  - { name: password_encryption, value: "scram-sha-256", for_patroni: 1 }
  - { name: cluster_name, value: "'{{ pg_ver }}/main'", for_patroni: 0 }
  - { name: listen_addresses, value: "'*'", for_patroni: 0 }
  - { name: port, value: "5432", for_patroni: 0 }
  - { name: max_replication_slots, value: "5", for_patroni: 0 }
  
pg_user:
  - { name: replicator, passwd: "replicator", role: "REPLICATION" }
  - { name: barman, passwd: "barman", role: "REPLICATION,SUPERUSER" }
  - { name: postgres, passwd: "vagrant", role: "SUPERUSER" }
  - { name: monitor, passwd: "monitor", role: "login" }
  - { name: rewind_user, passwd: "WfcuDtEzEbLCHBaYQXX3", role: "REPLICATION,SUPERUSER" }
  - { name: "{{ app_user }}", passwd: "{{ app_passwd }}", role: "login" }

pg_hba:
  - { src: "{{ hostvars[groups['postgresql'][0]].inventory_hostname }}.home.local", user: replicator, db: replication }
  - { src: "{{ hostvars[groups['postgresql'][0]].inventory_hostname }}.home.local", user: rewind_user, db: all }
  - { src: "{{ hostvars[groups['postgresql'][0]].inventory_hostname }}.home.local", user: postgres, db: all }
  - { src: "{{ hostvars[groups['postgresql'][0]].inventory_hostname }}.home.local", user: monitor, db: postgres }
  - { src: "{{ hostvars[groups['postgresql'][0]].inventory_hostname }}.home.local", user: app, db: "{{ app_db }}" }
  - { src: cluster-db.home.local, user: "{{ app_user }}", db: "{{ app_db }}" }
  - { src: 192.168.50.0/24, user: postgres, db: all }
  - { src: 192.168.50.0/24, user: "{{ app_user }}", db: "{{ app_db }}" }
      