---
network:
  version: 2
  renderer: networkd
  ethernets:
    enp0s8:
      addresses:
      - {{ ip_addr }}/24
{% if gp_mtu is defined %}
      mtu: {{ gp_mtu }}
{% endif %}
      routes:
      - to: 0.0.0.0/0
        via: {{ ip_route }}
    enp0s9:
      addresses:
      - {{ ip_addr_mg }}/24
